Eklentiler/Eklentiler.Widgets.NivoSlider/Controllers/WidgetsNivoSliderController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Core;
using Core.Önbellek;
using Eklentiler.Widgets.NivoSlider.Models;
using Services.Yapılandırma;
using Services.Localization;
using Services.Medya;
using Services.Güvenlik;
using Services.Siteler;
using Web.Framework;
using Web.Framework.Controllers;

namespace Eklentiler.Widgets.NivoSlider.Controllers
{
    [Area(AreaAdları.Admin)]
    public class WidgetsNivoSliderController : TemelEklentiController
    {
        private readonly IWorkContext _workContext;
        private readonly ISiteServisi _siteServisi;
        private readonly IResimServisi _resimServisi;
        private readonly IAyarlarServisi _ayarlarServisi;
        private readonly IİzinServisi _izinServisi;
        private readonly ILocalizationService _localizationService;

        public WidgetsNivoSliderController(IWorkContext workContext,
            ISiteServisi siteServisi,
            IResimServisi resimServisi,
            IAyarlarServisi ayarlarServisi,
            IİzinServisi izinServisi,
            ILocalizationService localizationService)
        {
            this._workContext = workContext;
            this._siteServisi = siteServisi;
            this._resimServisi = resimServisi;
            this._ayarlarServisi = ayarlarServisi;
            this._izinServisi = izinServisi;
            this._localizationService = localizationService;
        }
        public IActionResult Configure()
        {
            if (!_izinServisi.YetkiVer(StandartİzinSağlayıcı.EklentileriYönet))
                return ErişimEngellendiGörünümü();
            
            var siteGörünümü = this.AktifSiteKapsamYapılandırmaAl(_siteServisi, _workContext);
            var nivoSliderSettings = _ayarlarServisi.AyarYükle<NivoSliderSettings>(siteGörünümü);
            var model = new ConfigurationModel
            {
                Picture1Id = nivoSliderSettings.Picture1Id,
                Text1 = nivoSliderSettings.Text1,
                Link1 = nivoSliderSettings.Link1,
                Picture2Id = nivoSliderSettings.Picture2Id,
                Text2 = nivoSliderSettings.Text2,
                Link2 = nivoSliderSettings.Link2,
                Picture3Id = nivoSliderSettings.Picture3Id,
                Text3 = nivoSliderSettings.Text3,
                Link3 = nivoSliderSettings.Link3,
                Picture4Id = nivoSliderSettings.Picture4Id,
                Text4 = nivoSliderSettings.Text4,
                Link4 = nivoSliderSettings.Link4,
                Picture5Id = nivoSliderSettings.Picture5Id,
                Text5 = nivoSliderSettings.Text5,
                Link5 = nivoSliderSettings.Link5,
                ActiveStoreScopeConfiguration = siteGörünümü
            };

            if (siteGörünümü > 0)
            {
                model.Picture1Id_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Picture1Id, siteGörünümü);
                model.Text1_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Text1, siteGörünümü);
                model.Link1_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Link1, siteGörünümü);
                model.Picture2Id_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Picture2Id, siteGörünümü);
                model.Text2_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Text2, siteGörünümü);
                model.Link2_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Link2, siteGörünümü);
                model.Picture3Id_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Picture3Id, siteGörünümü);
                model.Text3_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Text3, siteGörünümü);
                model.Link3_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Link3, siteGörünümü);
                model.Picture4Id_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Picture4Id, siteGörünümü);
                model.Text4_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Text4, siteGörünümü);
                model.Link4_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Link4, siteGörünümü);
                model.Picture5Id_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Picture5Id, siteGörünümü);
                model.Text5_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Text5, siteGörünümü);
                model.Link5_OverrideForStore = _ayarlarServisi.AyarlarMevcut(nivoSliderSettings, x => x.Link5, siteGörünümü);
            }

            return View("~/Eklentiler/Widgets.NivoSlider/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public IActionResult Configure(ConfigurationModel model)
        {
            if (!_izinServisi.YetkiVer(StandartİzinSağlayıcı.EklentileriYönet))
                return ErişimEngellendiGörünümü();

            var siteGörünümü = this.AktifSiteKapsamYapılandırmaAl(_siteServisi, _workContext);
            var nivoSliderSettings = _ayarlarServisi.AyarYükle<NivoSliderSettings>(siteGörünümü);

            var previousPictureIds = new[]
            {
                nivoSliderSettings.Picture1Id,
                nivoSliderSettings.Picture2Id,
                nivoSliderSettings.Picture3Id,
                nivoSliderSettings.Picture4Id,
                nivoSliderSettings.Picture5Id
            };

            nivoSliderSettings.Picture1Id = model.Picture1Id;
            nivoSliderSettings.Text1 = model.Text1;
            nivoSliderSettings.Link1 = model.Link1;
            nivoSliderSettings.Picture2Id = model.Picture2Id;
            nivoSliderSettings.Text2 = model.Text2;
            nivoSliderSettings.Link2 = model.Link2;
            nivoSliderSettings.Picture3Id = model.Picture3Id;
            nivoSliderSettings.Text3 = model.Text3;
            nivoSliderSettings.Link3 = model.Link3;
            nivoSliderSettings.Picture4Id = model.Picture4Id;
            nivoSliderSettings.Text4 = model.Text4;
            nivoSliderSettings.Link4 = model.Link4;
            nivoSliderSettings.Picture5Id = model.Picture5Id;
            nivoSliderSettings.Text5 = model.Text5;
            nivoSliderSettings.Link5 = model.Link5;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update 
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Picture1Id, model.Picture1Id_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Text1, model.Text1_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Link1, model.Link1_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Picture2Id, model.Picture2Id_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Text2, model.Text2_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Link2, model.Link2_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Picture3Id, model.Picture3Id_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Text3, model.Text3_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Link3, model.Link3_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Picture4Id, model.Picture4Id_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Text4, model.Text4_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Link4, model.Link4_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Picture5Id, model.Picture5Id_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Text5, model.Text5_OverrideForStore, siteGörünümü, false);
            _ayarlarServisi.SaveSettingOverridablePerStore(nivoSliderSettings, x => x.Link5, model.Link5_OverrideForStore, siteGörünümü, false);
            */
            //now clear settings cache
            _ayarlarServisi.ÖnbelleğiTemizle();

            //get current picture identifiers
            var currentPictureIds = new[]
            {
                nivoSliderSettings.Picture1Id,
                nivoSliderSettings.Picture2Id,
                nivoSliderSettings.Picture3Id,
                nivoSliderSettings.Picture4Id,
                nivoSliderSettings.Picture5Id
            };

            //delete an old picture (if deleted or updated)
            foreach (var pictureId in previousPictureIds.Except(currentPictureIds))
            {
                var previousPicture = _resimServisi.ResimAlId(pictureId);
                if (previousPicture != null)
                    _resimServisi.ResimSil(previousPicture);
            }

            BaşarılıBildirimi(_localizationService.GetResource("Admin.Plugins.Saved"));
            return Configure();
        }
    }
}

Eklentiler/Eklentiler.Widgets.NivoSlider/Views/Configure.cshtml
@model Nop.Plugin.Widgets.NivoSlider.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")
<form asp-controller="WidgetsNivoSlider" asp-action="Configure" method="post">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                @T("Plugins.Widgets.NivoSlider.Picture1")
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Picture1Id_OverrideForStore" asp-input="Picture1Id" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Picture1Id" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Picture1Id" />
                        <span asp-validation-for="Picture1Id"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Text1_OverrideForStore" asp-input="Text1" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Text1" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Text1" />
                        <span asp-validation-for="Text1"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Link1_OverrideForStore" asp-input="Link1" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Link1" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Link1" />
                        <span asp-validation-for="Link1"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                @T("Plugins.Widgets.NivoSlider.Picture2")
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Picture2Id_OverrideForStore" asp-input="Picture2Id" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Picture2Id" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Picture2Id" />
                        <span asp-validation-for="Picture2Id"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Text2_OverrideForStore" asp-input="Text2" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Text2" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Text2" />
                        <span asp-validation-for="Text2"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Link2_OverrideForStore" asp-input="Link2" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Link2" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Link2" />
                        <span asp-validation-for="Link2"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                @T("Plugins.Widgets.NivoSlider.Picture3")
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Picture3Id_OverrideForStore" asp-input="Picture3Id" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Picture3Id" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Picture3Id" />
                        <span asp-validation-for="Picture3Id"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Text3_OverrideForStore" asp-input="Text3" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Text3" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Text3" />
                        <span asp-validation-for="Text3"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Link3_OverrideForStore" asp-input="Link3" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Link3" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Link3" />
                        <span asp-validation-for="Link3"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                @T("Plugins.Widgets.NivoSlider.Picture4")
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Picture4Id_OverrideForStore" asp-input="Picture4Id" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Picture4Id" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Picture4Id" />
                        <span asp-validation-for="Picture4Id"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Text4_OverrideForStore" asp-input="Text4" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Text4" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Text4" />
                        <span asp-validation-for="Text4"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Link4_OverrideForStore" asp-input="Link4" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Link4" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Link4" />
                        <span asp-validation-for="Link4"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                @T("Plugins.Widgets.NivoSlider.Picture5")
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Picture5Id_OverrideForStore" asp-input="Picture5Id" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Picture5Id" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Picture5Id" />
                        <span asp-validation-for="Picture5Id"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Text5_OverrideForStore" asp-input="Text5" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Text5" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Text5" />
                        <span asp-validation-for="Text5"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Link5_OverrideForStore" asp-input="Link5" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Link5" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Link5" />
                        <span asp-validation-for="Link5"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Eklentiler/Eklentiler.Widgets.NivoSlider/Views/PublicInfo.cshtml
@model Nop.Plugin.Widgets.NivoSlider.Models.PublicInfoModel
@{
    Layout = "";

    Html.AddScriptParts(ResourceLocation.Footer, "~/Plugins/Widgets.NivoSlider/Scripts/jquery.nivo.slider.js");
    Html.AddCssFileParts("~/Plugins/Widgets.NivoSlider/Content/nivoslider/nivo-slider.css");
    Html.AddCssFileParts("~/Plugins/Widgets.NivoSlider/Content/nivoslider/themes/custom/custom.css");
}

<div class="slider-wrapper theme-custom">
    <div id="nivo-slider" class="nivoSlider">
        @{
            var dataSlide1 = new ViewDataDictionary(ViewData)
            {
                {"pictureUrl", Model.Picture1Url},
                { "text", Model.Text1},
                { "link", Model.Link1}
            };

            @await Html.PartialAsync("~/Plugins/Widgets.NivoSlider/Views/_PublicInfo.SliderLine.cshtml", dataSlide1)
        }
        
        @{
            var dataSlide2 = new ViewDataDictionary(ViewData)
            {
                {"pictureUrl", Model.Picture2Url},
                { "text", Model.Text2},
                { "link", Model.Link2}
            };

            @await Html.PartialAsync("~/Plugins/Widgets.NivoSlider/Views/_PublicInfo.SliderLine.cshtml", dataSlide2)
        }
        
        @{
            var dataSlide3 = new ViewDataDictionary(ViewData)
            {
                {"pictureUrl", Model.Picture3Url},
                { "text", Model.Text3},
                { "link", Model.Link3},
                { "dataTransition", "slideInLeft"}
            };

            @await Html.PartialAsync("~/Plugins/Widgets.NivoSlider/Views/_PublicInfo.SliderLine.cshtml", dataSlide3)
        }

        @{
            var dataSlide4 = new ViewDataDictionary(ViewData)
            {
                {"pictureUrl", Model.Picture4Url},
                { "text", Model.Text4},
                { "link", Model.Link4}
            };

            @await Html.PartialAsync("~/Plugins/Widgets.NivoSlider/Views/_PublicInfo.SliderLine.cshtml", dataSlide4)
        }
        
        @{
            var dataSlide5 = new ViewDataDictionary(ViewData)
            {
                {"pictureUrl", Model.Picture5Url},
                { "text", Model.Text5},
                { "link", Model.Link5}
            };

            @await Html.PartialAsync("~/Plugins/Widgets.NivoSlider/Views/_PublicInfo.SliderLine.cshtml", dataSlide5)
        }
    </div>
</div>
<script type="text/javascript" asp-location="Footer">
    $(window).load(function () {
        $('#nivo-slider').nivoSlider();
    });
</script>

Eklentiler/Eklentiler.Widgets.NivoSlider/Views/_PublicInfo.SliderLine.cshtml
@model Nop.Plugin.Widgets.NivoSlider.Models.PublicInfoModel

@{
    var pictureUrl = ViewData["pictureUrl"]?.ToString() ?? "";
    var link = ViewData["link"]?.ToString() ?? "";
    var dataTransition = ViewData["dataTransition"]?.ToString() ?? "";
    var text = ViewData["text"]?.ToString() ?? "";

    if (!string.IsNullOrEmpty(pictureUrl))
    {
        if (!string.IsNullOrEmpty(link))
        {
            <a href="@link">
                <img src="@pictureUrl" data-thumb="@pictureUrl" data-transition="@dataTransition" alt="" title="@text" />
            </a>
        }
        else
        {
            <img src="@pictureUrl" data-thumb="@pictureUrl" data-transition="@dataTransition" alt="" title="@text" />
        }
    }
}